version: 1

tables:
  clinical_trials: 
    to_request: True
    source_gcs_project_id: 'tbqc-demo-'
    source_gcs_bucket_name: 'tbqc-demo-landing-bucket'
    source_file_params: 'pipeline/0_landing_to_raw/manual_files/params/clinical_trials_params.json'
    destination_bq_project_id: 'tbqc-demo-'
    destination_bq_dataset_name: '1_raw'
    destination_bq_table_name: 'clinical_trials'
    write_mode: 'TRUNCATE'
  drugs: 
    to_request: False
    source_gcs_project_id: 'tbqc-demo-'
    source_gcs_bucket_name: 'tbqc-demo-landing-bucket'
    source_file_params: 'pipeline/0_landing_to_raw/manual_files/params/drugs_params.json'
    destination_bq_project_id: 'tbqc-demo-'
    destination_bq_dataset_name: '1_raw'
    destination_bq_table_name: 'drugs'
    write_mode: 'TRUNCATE'
  pubmed: 
    to_request: False
    source_gcs_project_id: 'tbqc-demo-'
    source_gcs_bucket_name: 'tbqc-demo-landing-bucket'
    source_file_params: 'pipeline/0_landing_to_raw/manual_files/params/pubmed_params.json'
    destination_bq_project_id: 'tbqc-demo-'
    destination_bq_dataset_name: '1_raw'
    destination_bq_table_name: 'pubmed'
    write_mode: 'TRUNCATE'

data_quality :
  gcs_project_id: 'tbqc-demo-'
  gcs_data_path: 'data_quality'
  gcs_file_stats_filename: 'file_stats'
  gcs_rows_stats_filename: 'rows_stats'
  gcs_data_invalid_filename: 'data_invalid'
  bq_project_id: 'tbqc-demo-'
  bq_dataset_name: '99_data_quality'
  bq_file_stats_table_name: 'file_stats'
  bq_rows_stats_table_name: 'rows_stats'
  bq_data_invalid_table_name: 'data_invalid'