name: Deploy to Cloud Run 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with: 
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build Docker image
      run: |
        IMAGE_NAME=europe-west1-docker.pkg.dev/tbqc-demo-dev/tbqc-demo-ar-application/landing-to-raw
        docker build -t $IMAGE_NAME .
    
    - name: Push Docker image to Artifact Registry
      run: |
        IMAGE_NAME=europe-west1-docker.pkg.dev/tbqc-demo-dev/tbqc-demo-ar-application/landing-to-raw
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy landing-to-raw \
          --image europe-west1-docker.pkg.dev/tbqc-demo-dev/tbqc-demo-ar-application/landing-to-raw:latest \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated
